language: python
branches:
  only:
  - master
before_install:
- sudo apt-get update -qq
- sudo apt-get install nodejs optipng jpegtran
- npm install uglifyjs
install:
- pip install -r ./requirements.txt
script:
- make publish github
env:
  global:
    secure: nttDFFv97xJ6eZZk1eIgkP1+SCl5FrmZu012BF6/AnAbIKwx6L126kK5efKGaPX1qtnChngXM/KXxNEve5bhq3FilzWBjJbaomqOTn+Y/fWo5iwEqsfRKqpqiNLorsGFnflKwcR4L+IK+xUm1iP3xj8eHMuHhs0Hfw79Q6zduS4gXiQvace+5Dg7VKQi7sxtxnP0rrsthlJdhYM9JCNi+I89HWQ0NkseC93o8U4aclcJsmET7ULdKNnO8VgKRh9xN5xi3Qvv6jA66WO3cFZetO/JvG0loqIayKLD2o8qHdGXB302pyZjxpVqiU8or8sKawhN6B2YucCT+7nMuuRiaQAw2oYvDK1G2EtxJN1U4F7qeRZgA+wTCYd9tIgzatyhioTebRbx1APtWoEJtghDY5eCNKAlaWUAir9I4UngKB75CE46XYQg9OeopzI/nq4EbxFiS2NdrpJta1Vpd0Jxu7xENLULujbXJ+BGPBmLeB96jZo3k7Ksn0/tOnucdmxdDNW+di89ha3bHzTY6iVcl2T5r+IQzxkTaXbZgms6meXA/2LxaUUe4eKQtnDyfimUD6L25+MoCam4bm0U+m9MZF/W5XPBPkm1zP+nj4WlC9pKgYGqFhzoAqvPzP+J2O5WPvyiR/+bwhSUbZsPlxaAixZGUF5eVXPj9eS1lt5z7QU=
