language: python
branches:
  only:
  - master
before_install:
  - sudo apt-get update -qq
  - sudo apt-get install nodejs
  - npm install uglifyjs
install:
- pip install -r ./requirements.txt
script:
- make publish github
