language: python
branches:
  only:
  - master
before_install:
- sudo apt-get update -qq
- sudo apt-get install nodejs libjpeg-progs
- npm install uglifyjs
install:
- pip install -r ./requirements.txt
- pelican-themes -s ./plumage/
script:
- make publish github
