language: python
branches:
  only:
    - live
before_install:
  - sudo apt-get update -qq
  - sudo apt-get install nodejs libjpeg-progs
  - npm install uglifyjs
install:
  - pip install -r ./requirements.txt
  - pelican-themes -s ./plumage/
script:
  - make publish github
deploy:
  provider: pages
  skip_cleanup: true
  github_token: "$GITHUB_TOKEN"
  keep_history: false
  on:
    branch: gh-pages
env:
  global:
    secure: N/eip7rDtAjdmSBUecIDQrA2TZRPd487/aH9XCLzX+ihOkfYJ4hDZBopvEFWr6Bw4ZHP+Fk2fBI6m/ZfxGutCyIZq7CTiK1yo7Z9J/AO46z/wRCgrNpRRKyI1NtwYwahMuEVqLkZ48fpenhyjyKJ4vdqBGIbpeiYLZBYJ0dpY8rk/9NtyM5RMfmi+RyJl1VGn3YTstF/+UhYMMcVi6IZIwqIEb6BelZPl4Xv09l5rePag0ETGcvGPS5CvlalXmt+zD0vVa4tfxLWR22U7WUf56Tp7MFjEHEWc8wh/weI/JdSEREfg8dRhwIbagC+Nm7nTc5I9GdbR37GAcpXEgUykpJ84uYOlqV1utNFKyYtScqXqCP6nXaVs8QxszBnaAHP0U7utfbgzpOE5gLywGA9I5ZPZgX9PhJw4w6EbdILjjbObL+suANBLxDggwUVyh2bYB0kStwrr0rVIHJ0vPNkrO8Mr6HpiAbSiyXsihadtqQuVWXYmSYgvDKyrEmSjsdk41sw/cmrAACo3IbhJ0o2odoExPN67b5hhQWrjJ/iOymgNsLLv7vNqEO8+jXpwQACALg2BWfarGOuIGsiJb2g8IufZpPX0XsBmF4On6UVPWML+tBjzrUGgqB6VmFBEomL4+mHJkrX3ihjX5CEHogdfaO4EHf5S5xYj9shH3uYnnA=
