name: Pelican site with Plumage

on:
  # Trigger the workflow on push or pull request,
  # but only for the master branch
  push:
    branches:
      - live

jobs:
  prepare:
    name: Preparation
    runs-on: ubuntu-20.04

    steps:
    # - name: update system
      # run: sudo apt update && sudo apt upgrade -y
    - uses: actions/checkout@v2.3.4
    - uses: actions/setup-java@v2
      with:
        distribution: 'adopt'
        java-version: '8'
    - uses: actions/setup-node@v2
      with:
        node-version: '16'
        # cache: 'npm'
    - uses: actions/setup-python@v2
      with:
        python-version: 3.9
    - run: |
        python -m pip install --upgrade poetry
    - uses: actions/cache@v2
      with:
        path: ~/.cache/pypoetry/virtualenvs
        key: ${{ runner.os }}-poetry-${{ hashFiles('poetry.lock') }}
    - run: |
        poetry install
    - run: |
        poetry run pelican --settings ./publishconf.py --verbose ./content
  
    - name: Deploy to GitHub Pages
      uses: Cecilapp/GitHub-Pages-deploy@v3
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        email: oss@kmonsoor.com
        build_dir: ./output
        commit_message: ${{ github.event.head_commit.message }}
        cname: blog.kmonsoor.com

