name: Pelican site with Plumage

# Controls when the workflow will run
on:
  pull_request:

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  validate:
    name: Validate the Pull-request
    runs-on: ubuntu-20.04

    steps:
    # - name: update system
      # run: sudo apt update && sudo apt upgrade -y
    - uses: actions/checkout@v3
    - uses: actions/setup-java@v2.3.1
      with:
        distribution: 'temurin'
        java-version: '11'
        java-package: jre
    - uses: actions/setup-node@v2
      with:
        node-version: '16'
    - uses: actions/setup-python@v4
      with:
        python-version: 3.9
    - uses: Gr1N/setup-poetry@v8
      with:
        poetry-version: 1.2.2
    - uses: actions/cache@v2
      with:
        path: ~/.cache/pypoetry/virtualenvs
        key: ${{ runner.os }}-poetry-${{ hashFiles('poetry.lock') }}
    - run: |
        poetry install
    - run: |
        poetry run pelican --settings ./publishconf.py ./content

